"""Deterministic EOD report generation — same contract as fr_report.

EOD is the after-close companion to FR: what moved, what plausibly drove it,
what to watch tomorrow. Its tables are as mechanical as FR's, so they belong to
code for the same reason — the model's job is attribution and judgement, not
transporting a sector scoreboard through the conversation.

Two EOD-specific rules the generator enforces so the prose cannot quietly break
them (both from the EOD contract in CLAUDE.md):

* Attribution is never asserted as measured causation. §4 ships the drivers'
  own moves; any impact figure the prose adds must be labelled an estimate.
* "Tomorrow" is a volatility-derived band from ATR, never a point forecast.
  §7's table is generated that way and says so in its own caption.
"""
from __future__ import annotations

from typing import Any

from eod_render import (
    render_asset_classes,
    render_crypto_movers,
    render_expected_ranges,
    render_movers,
    render_scoreboard,
)
from fr_render import render_table
from fr_report import PROSE_PLACEHOLDER, marker_close, marker_open
from fr_sections import EOD_SECTIONS, REPORT_SCHEMA_VERSION, _resolve

EOD_PROSE_SLOTS: tuple[tuple[str, str], ...] = (
    ("verify", "§0 — settle yesterday's calls against today's close"),
    ("tape", "§1 — what kind of day, in one line plus context"),
    ("sectors", "§2 — leaders/laggards, cyclical vs defensive"),
    ("movers", "§3 — the movers worth explaining"),
    ("drivers", "§4 — driver attribution, with LABELLED sensitivity estimates only"),
    ("crossasset", "§5 — bonds, commodities, dollar, crypto"),
    ("confirm", "§6 — did today confirm or break the morning FR's read"),
    ("tomorrow", "§7 — the single biggest catalyst + today's named gradable calls"),
    ("synthesis", "§8 — 4–6 connected sentences + the daily self-grading readout"),
)

EOD_TITLES: tuple[tuple[str, str], ...] = (
    ("0", "Verification"),
    ("1", "The Tape"),
    ("2", "Sector Scoreboard"),
    ("3", "Movers"),
    ("4", "Driver Attribution"),
    ("5", "Cross-Asset Close"),
    ("6", "Confirm / Refute the Morning FR"),
    ("7", "What to Watch Tomorrow"),
    ("8", "Synthesis"),
)

# Derived rather than written out a third time: section number, title and slot
# are three parallel orderings of the same nine sections, and a hand-maintained
# mapping is the one that can drift silently (a wrong pairing puts the prose
# under the wrong heading instead of raising).
_SLOT_FOR_SECTION = {
    number: slot for (number, _), (slot, _) in zip(EOD_TITLES, EOD_PROSE_SLOTS)
}
assert len(_SLOT_FOR_SECTION) == len(EOD_TITLES) == len(EOD_PROSE_SLOTS)


def _slot(key: str) -> str:
    return f"{marker_open(key)}\n{PROSE_PLACEHOLDER}\n{marker_close(key)}"


def _movers_universe(raw: dict) -> Any:
    """The mover universe, falling back to the watchlist when it failed.

    A failed source is a ``{"_value": FAIL}`` dict, which is truthy — so `or`
    would have kept the failure and never reached the fallback.
    """
    movers = raw.get("quotes_batch_movers")
    return movers if isinstance(movers, list) else raw.get("quotes_batch_watchlist")


def build_eod_report(raw: dict, derived: dict, date: str) -> str:
    """The complete EOD report with every deterministic block populated."""
    src = _resolve(raw, derived)
    by_number = {s.number: s for s in EOD_SECTIONS}

    out: list[str] = [
        f"# End-of-Day Report — {date}",
        "",
        f"*Report schema v{REPORT_SCHEMA_VERSION}. Tables generated by "
        "`fr_collect.py --mode eod --emit-report`; prose written into the marked slots.*",
        "",
        "> Attribution below pairs each driver's move with each asset's move. It is NOT "
        "measured causation: any impact figure in the prose is a labelled sensitivity "
        "estimate. Tomorrow's ranges are volatility bands, not forecasts.",
        "",
    ]

    for number, title in EOD_TITLES:
        out += [f"## {number}. {title}", ""]
        sec = by_number.get(number)
        if sec is not None and sec.fields:
            out += [render_table(src, sec), ""]
        if number == "2":
            out += [render_scoreboard(raw.get("quotes_batch_spdrs"), "Sector ETF"), ""]
        elif number == "3":
            out += [
                "### Top gainers and losers (ranked in code from today's %)",
                "",
                render_movers(_movers_universe(raw)),
                "",
                "### Research watchlist",
                "",
                render_scoreboard(raw.get("quotes_batch_watchlist"), "Watchlist"),
                "",
            ]
        elif number == "5":
            out += [
                "### Asset classes",
                "",
                render_asset_classes(raw.get("asset_class_returns")),
                "",
                "### Crypto",
                "",
                render_crypto_movers(raw.get("crypto_batch")),
                "",
            ]
        elif number == "7":
            out += [
                "### Expected ranges (ATR-derived, not a forecast)",
                "",
                render_expected_ranges(raw.get("technicals_SPY"), raw.get("market_overview")),
                "",
            ]
        out += [_slot(_SLOT_FOR_SECTION[number]), ""]

    return "\n".join(out)


def eod_report_path(reports_dir, date: str):
    return reports_dir / f"{date}-eod.md"
