"""Inject model-written prose into the collector-generated report's slots.

The report arrives with delimited, empty slots. This fills them in place and
touches nothing else, so the deterministic tables can never be rewritten by
accident — the only bytes that change are between a matched marker pair.

Idempotent: markers survive injection, so a slot can be refilled (an intraday
re-run, a correction) without regenerating the report.

Usage:
    python scripts/fr_prose.py --report FILE --set s3=@prose_s3.md --set s5="..."
    python scripts/fr_prose.py --report FILE --json prose.json
    python scripts/fr_prose.py --report FILE --list      # unfilled slots
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

from eod_report import EOD_PROSE_SLOTS
from fr_report import PROSE_PLACEHOLDER, PROSE_SLOTS, marker_close, marker_open


class ProseError(RuntimeError):
    """Raised when the report's structure is not what injection requires."""


def slot_pattern(key: str) -> re.Pattern[str]:
    return re.compile(
        rf"({re.escape(marker_open(key))})\n.*?\n({re.escape(marker_close(key))})",
        re.DOTALL,
    )


def slots_for(report: str) -> tuple[tuple[str, str], ...]:
    """FR and EOD reports use different slot names — pick by what's in the file.

    Detection is by marker count rather than by the title line, so a report that
    is renamed or partially filled still validates against the right slot set.
    """
    def present(slots: tuple[tuple[str, str], ...]) -> int:
        return sum(1 for k, _ in slots if marker_open(k) in report)

    return EOD_PROSE_SLOTS if present(EOD_PROSE_SLOTS) > present(PROSE_SLOTS) else PROSE_SLOTS


def known_keys(report: str = "") -> set[str]:
    return {k for k, _ in slots_for(report)}


def inject(report: str, key: str, text: str) -> str:
    """Replace the body of one slot. Fails loudly rather than guessing.

    A missing marker means the report was generated by a different version, or
    was hand-edited — either way, silently appending would corrupt it.
    """
    if key not in known_keys(report):
        raise ProseError(
            f"unknown prose slot {key!r}; known: {sorted(known_keys(report))}"
        )
    pattern = slot_pattern(key)
    matches = pattern.findall(report)
    if not matches:
        raise ProseError(
            f"prose slot {key!r} not found in report — expected "
            f"{marker_open(key)} ... {marker_close(key)}"
        )
    if len(matches) > 1:
        raise ProseError(f"prose slot {key!r} appears {len(matches)} times; refusing to guess")
    body = text.strip()
    if not body:
        raise ProseError(f"refusing to write empty prose into slot {key!r}")
    return pattern.sub(lambda m: f"{m.group(1)}\n{body}\n{m.group(2)}", report, count=1)


def inject_all(report: str, prose: dict[str, str]) -> str:
    for key, text in prose.items():
        report = inject(report, key, text)
    return report


def unfilled(report: str) -> list[str]:
    """Slots still holding the placeholder."""
    out = []
    for key, _ in slots_for(report):
        m = slot_pattern(key).search(report)
        if m is None or PROSE_PLACEHOLDER in m.group(0):
            out.append(key)
    return out


def _parse_set(pairs: list[str]) -> dict[str, str]:
    prose: dict[str, str] = {}
    for pair in pairs:
        if "=" not in pair:
            raise ProseError(f"--set expects key=value or key=@file, got {pair!r}")
        key, _, value = pair.partition("=")
        prose[key.strip()] = (
            Path(value[1:]).read_text(encoding="utf-8") if value.startswith("@") else value
        )
    return prose


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--report", required=True, type=Path)
    ap.add_argument("--set", action="append", default=[], dest="sets")
    ap.add_argument("--json", type=Path, help="JSON file of {slot: prose}")
    ap.add_argument("--list", action="store_true", help="list unfilled slots and exit")
    args = ap.parse_args()

    if not args.report.exists():
        print(f"report not found: {args.report}", file=sys.stderr)
        return 2
    report = args.report.read_text(encoding="utf-8")

    if args.list:
        remaining = unfilled(report)
        print("\n".join(remaining) if remaining else "all slots filled")
        return 0

    try:
        prose = _parse_set(args.sets)
        if args.json:
            prose.update(json.loads(args.json.read_text(encoding="utf-8")))
        if not prose:
            raise ProseError("nothing to inject — pass --set or --json")
        updated = inject_all(report, prose)
    except (ProseError, json.JSONDecodeError, OSError) as e:
        print(f"prose injection failed: {e}", file=sys.stderr)
        return 1

    args.report.write_text(updated, encoding="utf-8")
    remaining = unfilled(updated)
    print(f"filled {len(prose)} slot(s); {len(remaining)} remaining: {', '.join(remaining) or 'none'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
